[package]

name = "rcalc"
version = "0.17.0"
authors = [ "libfud" ]

[dependencies.matrix]
path = "src/lib/matrix"
[dependencies.types]
path = "src/lib/types"
[dependencies.parse]
path = "src/lib/parse"

[dependencies.num]
path = "/home/libfud/build/num"

[dependencies.readline]
version = "*"